### ISSUE TITLE
RET cc=true - Cycle Duration

### ISSUE THREAD

**Issue by fpiribauer** [Gekkio/gb-ctr#13]
The M-cycle duration for conditional RET cc=true is listed as "4". I'm not sure if this is correct. PanDocs and the gblargg instr_timing test think that "5" is the correct answer.

**Comment by Gekkio** [comment]
Thanks, good catch! I've clearly gotten the data of RET and RET cc mixed somewhere :thinking:
I'll rerun the CPU core simulations and fix the info for that instruction
