### ISSUE TITLE
Number of SP-- in PUSH rr

### ISSUE THREAD

**Issue by afilini** [Gekkio/gb-ctr#7]
I'm still pretty new to those stuff so I could definitely be wrong, but.. is the triple decrement here actually right or is it a mistake? Because it looks like `POP rr` only increments the stack pointer twice, so it seems a bit weird to me that doing a `PUSH` followed by a `POP` doesn't actually restore the same `SP` as before.

https://github.com/Gekkio/gb-ctr/blob/master/chapter/cpu/instruction-set.tex#L713-L715

Awesome work btw, I love the timing diagrams in this manual!!

**Comment by Gekkio** [comment]
Yeah it's a copy-paste mistake. I just merged a relevant pull request, so it's fixed now 😄 There seems to be a problem with the automated build right now, so it might take a while until the PDF is updated.
